# Form implementation generated from reading ui file 'Nova_inter.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(927, 490)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_fundo = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_fundo.setGeometry(QtCore.QRect(0, 0, 934, 491))
        self.frame_fundo.setStyleSheet("background-color: rgb(1, 132, 255);")
        self.frame_fundo.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_fundo.setObjectName("frame_fundo")
        self.frame = QtWidgets.QFrame(parent=self.frame_fundo)
        self.frame.setGeometry(QtCore.QRect(110, 50, 451, 41))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setObjectName("frame")
        self.label_MSGUSUARIO = QtWidgets.QLabel(parent=self.frame)
        self.label_MSGUSUARIO.setGeometry(QtCore.QRect(10, 10, 431, 21))
        self.label_MSGUSUARIO.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_MSGUSUARIO.setText("")
        self.label_MSGUSUARIO.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label_MSGUSUARIO.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_MSGUSUARIO.setObjectName("label_MSGUSUARIO")
        self.label_TITULO = QtWidgets.QLabel(parent=self.frame_fundo)
        self.label_TITULO.setGeometry(QtCore.QRect(210, 10, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        self.label_TITULO.setFont(font)
        self.label_TITULO.setStyleSheet("background-color: rgb(255, 255,100);")
        self.label_TITULO.setObjectName("label_TITULO")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame_fundo)
        self.frame_2.setGeometry(QtCore.QRect(33, 110, 661, 291))
        font = QtGui.QFont()
        font.setBold(True)
        self.frame_2.setFont(font)
        self.frame_2.setStyleSheet("background-color: rgb(0, 85, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setObjectName("frame_2")
        self.textEdit_MATRIZ_A = QtWidgets.QTextEdit(parent=self.frame_2)
        self.textEdit_MATRIZ_A.setGeometry(QtCore.QRect(10, 30, 171, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_MATRIZ_A.setFont(font)
        self.textEdit_MATRIZ_A.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_MATRIZ_A.setObjectName("textEdit_MATRIZ_A")
        self.label_MATRIZ_A = QtWidgets.QLabel(parent=self.frame_2)
        self.label_MATRIZ_A.setGeometry(QtCore.QRect(10, -1, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.label_MATRIZ_A.setFont(font)
        self.label_MATRIZ_A.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label_MATRIZ_A.setObjectName("label_MATRIZ_A")
        self.textEdit_MATRIZ_B = QtWidgets.QTextEdit(parent=self.frame_2)
        self.textEdit_MATRIZ_B.setGeometry(QtCore.QRect(310, 30, 171, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        self.textEdit_MATRIZ_B.setFont(font)
        self.textEdit_MATRIZ_B.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_MATRIZ_B.setObjectName("textEdit_MATRIZ_B")
        self.label_MATRIZ_B = QtWidgets.QLabel(parent=self.frame_2)
        self.label_MATRIZ_B.setGeometry(QtCore.QRect(310, -1, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.label_MATRIZ_B.setFont(font)
        self.label_MATRIZ_B.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label_MATRIZ_B.setObjectName("label_MATRIZ_B")
        self.pushButton_SOMA = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_SOMA.setGeometry(QtCore.QRect(190, 40, 111, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.pushButton_SOMA.setFont(font)
        self.pushButton_SOMA.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButton_SOMA.setStyleSheet("\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.142, y1:0.0227273, x2:1, y2:0, stop:0 rgba(0, 50, 66, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    background-color: rgb(255, 221, 196);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"")
        self.pushButton_SOMA.setObjectName("pushButton_SOMA")
        self.pushButton_SUBTRAIR = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_SUBTRAIR.setGeometry(QtCore.QRect(190, 70, 111, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.pushButton_SUBTRAIR.setFont(font)
        self.pushButton_SUBTRAIR.setStyleSheet("\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.142, y1:0.0227273, x2:1, y2:0, stop:0 rgba(0, 50, 66, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    background-color: rgb(255, 221, 196);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"")
        self.pushButton_SUBTRAIR.setObjectName("pushButton_SUBTRAIR")
        self.pushButton_MULTIPLICAR = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_MULTIPLICAR.setGeometry(QtCore.QRect(190, 100, 111, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.pushButton_MULTIPLICAR.setFont(font)
        self.pushButton_MULTIPLICAR.setStyleSheet("\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.142, y1:0.0227273, x2:1, y2:0, stop:0 rgba(0, 50, 66, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    background-color: rgb(255, 221, 196);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"")
        self.pushButton_MULTIPLICAR.setObjectName("pushButton_MULTIPLICAR")
        self.pushButton_TRANSPOSTA_A = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_TRANSPOSTA_A.setGeometry(QtCore.QRect(10, 160, 141, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.pushButton_TRANSPOSTA_A.setFont(font)
        self.pushButton_TRANSPOSTA_A.setStyleSheet("\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.142, y1:0.0227273, x2:1, y2:0, stop:0 rgba(0, 50, 66, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    background-color: rgb(255, 221, 196);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"")
        self.pushButton_TRANSPOSTA_A.setObjectName("pushButton_TRANSPOSTA_A")
        self.pushButton_TRANSPOSTA_B = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_TRANSPOSTA_B.setGeometry(QtCore.QRect(310, 160, 141, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.pushButton_TRANSPOSTA_B.setFont(font)
        self.pushButton_TRANSPOSTA_B.setStyleSheet("\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.142, y1:0.0227273, x2:1, y2:0, stop:0 rgba(0, 50, 66, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    background-color: rgb(255, 221, 196);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"")
        self.pushButton_TRANSPOSTA_B.setObjectName("pushButton_TRANSPOSTA_B")
        self.frame_MAGICA = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_MAGICA.setGeometry(QtCore.QRect(490, 30, 151, 121))
        self.frame_MAGICA.setStyleSheet("background-color: rgb(0, 85, 0);")
        self.frame_MAGICA.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_MAGICA.setObjectName("frame_MAGICA")
        self.label_MAGICA = QtWidgets.QLabel(parent=self.frame_MAGICA)
        self.label_MAGICA.setGeometry(QtCore.QRect(10, 10, 131, 21))
        self.label_MAGICA.setStyleSheet("background-color: rgb(0, 85, 0);")
        self.label_MAGICA.setObjectName("label_MAGICA")
        self.pushButton_GERAR_MAGICA = QtWidgets.QPushButton(parent=self.frame_MAGICA)
        self.pushButton_GERAR_MAGICA.setGeometry(QtCore.QRect(20, 90, 111, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.pushButton_GERAR_MAGICA.setFont(font)
        self.pushButton_GERAR_MAGICA.setStyleSheet("\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.142, y1:0.0227273, x2:1, y2:0, stop:0 rgba(0, 50, 66, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    background-color: rgb(255, 221, 196);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"")
        self.pushButton_GERAR_MAGICA.setObjectName("pushButton_GERAR_MAGICA")
        self.lineEdit_ORDEM_MAGICA = QtWidgets.QLineEdit(parent=self.frame_MAGICA)
        self.lineEdit_ORDEM_MAGICA.setGeometry(QtCore.QRect(10, 50, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_ORDEM_MAGICA.setFont(font)
        self.lineEdit_ORDEM_MAGICA.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_ORDEM_MAGICA.setObjectName("lineEdit_ORDEM_MAGICA")
        self.pushButton_DET_A = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_DET_A.setGeometry(QtCore.QRect(10, 190, 141, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.pushButton_DET_A.setFont(font)
        self.pushButton_DET_A.setStyleSheet("\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.142, y1:0.0227273, x2:1, y2:0, stop:0 rgba(0, 50, 66, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    background-color: rgb(255, 221, 196);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"")
        self.pushButton_DET_A.setObjectName("pushButton_DET_A")
        self.pushButton_DETERMINANTE_B = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_DETERMINANTE_B.setGeometry(QtCore.QRect(310, 190, 141, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.pushButton_DETERMINANTE_B.setFont(font)
        self.pushButton_DETERMINANTE_B.setStyleSheet("\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.142, y1:0.0227273, x2:1, y2:0, stop:0 rgba(0, 50, 66, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    background-color: rgb(255, 221, 196);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"")
        self.pushButton_DETERMINANTE_B.setObjectName("pushButton_DETERMINANTE_B")
        self.pushButton_INV_B = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_INV_B.setGeometry(QtCore.QRect(310, 220, 141, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.pushButton_INV_B.setFont(font)
        self.pushButton_INV_B.setStyleSheet("\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.142, y1:0.0227273, x2:1, y2:0, stop:0 rgba(0, 50, 66, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    background-color: rgb(255, 221, 196);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"")
        self.pushButton_INV_B.setObjectName("pushButton_INV_B")
        self.pushButton_INV_A = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_INV_A.setGeometry(QtCore.QRect(10, 220, 141, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.pushButton_INV_A.setFont(font)
        self.pushButton_INV_A.setStyleSheet("\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.142, y1:0.0227273, x2:1, y2:0, stop:0 rgba(0, 50, 66, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    background-color: rgb(255, 221, 196);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"")
        self.pushButton_INV_A.setObjectName("pushButton_INV_A")
        self.textEdit_RESULTADO = QtWidgets.QTextEdit(parent=self.frame_fundo)
        self.textEdit_RESULTADO.setGeometry(QtCore.QRect(710, 130, 214, 171))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        self.textEdit_RESULTADO.setFont(font)
        self.textEdit_RESULTADO.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_RESULTADO.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.textEdit_RESULTADO.setMidLineWidth(0)
        self.textEdit_RESULTADO.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.textEdit_RESULTADO.setReadOnly(True)
        self.textEdit_RESULTADO.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.textEdit_RESULTADO.setObjectName("textEdit_RESULTADO")
        self.label_RESULTADO = QtWidgets.QLabel(parent=self.frame_fundo)
        self.label_RESULTADO.setGeometry(QtCore.QRect(740, 100, 161, 31))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_RESULTADO.setFont(font)
        self.label_RESULTADO.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_RESULTADO.setObjectName("label_RESULTADO")
        self.label_Emoji = QtWidgets.QLabel(parent=self.frame_fundo)
        self.label_Emoji.setGeometry(QtCore.QRect(710, 300, 219, 151))
        self.label_Emoji.setObjectName("label_Emoji")
        self.label = QtWidgets.QLabel(parent=self.frame_fundo)
        self.label.setGeometry(QtCore.QRect(20, 100, 691, 311))
        self.label.setObjectName("label")
        self.label_Balao211x51 = QtWidgets.QLabel(parent=self.frame_fundo)
        self.label_Balao211x51.setGeometry(QtCore.QRect(706, 82, 224, 51))
        self.label_Balao211x51.setObjectName("label_Balao211x51")
        self.label_AvISO61x51 = QtWidgets.QLabel(parent=self.frame_fundo)
        self.label_AvISO61x51.setGeometry(QtCore.QRect(570, 40, 61, 51))
        self.label_AvISO61x51.setObjectName("label_AvISO61x51")
        self.label_chao931x31 = QtWidgets.QLabel(parent=self.frame_fundo)
        self.label_chao931x31.setGeometry(QtCore.QRect(0, 460, 931, 31))
        self.label_chao931x31.setObjectName("label_chao931x31")
        self.label_Balao211x51.raise_()
        self.label.raise_()
        self.frame.raise_()
        self.label_TITULO.raise_()
        self.frame_2.raise_()
        self.textEdit_RESULTADO.raise_()
        self.label_RESULTADO.raise_()
        self.label_Emoji.raise_()
        self.label_AvISO61x51.raise_()
        self.label_chao931x31.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_MSGUSUARIO.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_TITULO.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#000000;\">CALCULADORA DE MATRIZES</span></p></body></html>"))
        self.label_MATRIZ_A.setText(_translate("MainWindow", "MATRIZ A"))
        self.label_MATRIZ_B.setText(_translate("MainWindow", "MATRIZ B"))
        self.pushButton_SOMA.setText(_translate("MainWindow", "SOMAR (+)"))
        self.pushButton_SUBTRAIR.setText(_translate("MainWindow", "SUBTRAIR (-)"))
        self.pushButton_MULTIPLICAR.setText(_translate("MainWindow", "MULTIPLICAR (X)"))
        self.pushButton_TRANSPOSTA_A.setText(_translate("MainWindow", "TRANSPOSTA DE A"))
        self.pushButton_TRANSPOSTA_B.setText(_translate("MainWindow", "TRANSPOSTA DE B"))
        self.label_MAGICA.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:700;\">MATRIZ MÁGICA</span></p></body></html>"))
        self.pushButton_GERAR_MAGICA.setText(_translate("MainWindow", "GERAR MATRIZ"))
        self.lineEdit_ORDEM_MAGICA.setPlaceholderText(_translate("MainWindow", "ORDEM DA MATRIZ"))
        self.pushButton_DET_A.setText(_translate("MainWindow", "DETERMINANTE DE A"))
        self.pushButton_DETERMINANTE_B.setText(_translate("MainWindow", "DETERMINANTE DE B"))
        self.pushButton_INV_B.setText(_translate("MainWindow", "INVERSA DE B"))
        self.pushButton_INV_A.setText(_translate("MainWindow", "INVERSA DE A"))
        self.textEdit_RESULTADO.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>"))
        self.label_RESULTADO.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#000000;\">RESULTADO</span></p></body></html>"))
        self.label_Emoji.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_Balao211x51.setText(_translate("MainWindow", "TextLabel"))
        self.label_AvISO61x51.setText(_translate("MainWindow", "TextLabel"))
        self.label_chao931x31.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
